In [2]:
import pandas as pd

In [3]:
s=pd.Series([10,20,30])

In [4]:
print(s)

0    10
1    20
2    30
dtype: int64


In [5]:
import numpy as np

In [6]:
a=np.array([10,20,30])

In [7]:
print(a)

[10 20 30]


In [8]:
b=np.array([[10,20,30],[20,30,40],[30,40,50]])

In [9]:
print(b)

[[10 20 30]
 [20 30 40]
 [30 40 50]]
